version: '3.1'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - db
        networks:
            - pacientes

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - redis
            - app
        networks:
            - pacientes

    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DATABASE: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            PGDATA: /data/postgres
        volumes:
            - ./.docker/postgres/dbdata:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - pacientes

    # redis
    redis:
        image: redis:latest
        networks:
            - pacientes

networks:
    pacientes:
        driver: bridge
